/*
 * This file is part of Adblock Plus <https://adblockplus.org/>,
 * Copyright (C) 2006-present eyeo GmbH
 *
 * Adblock Plus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Adblock Plus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Adblock Plus.  If not, see <http://www.gnu.org/licenses/>.
 */

/// JSON filter list model struct that corresponds to v2 filter lists generated by
/// [abp2blocklist](https://github.com/adblockplus/abp2blocklist).
public struct JSONFilterList: Decodable {
    public var version: String?
    public var expires: String?
    public var sources: FilterListV2Sources?
    public var rules: FilterListV2Rules?

    /// Parse a JSON filter list and store its data in the struct.
    /// - Parameter data: Data containing a JSON filter list.
    public init?(with data: Data) {
        let decoder = JSONDecoder()
        do {
            let list = try decoder.decode(JSONFilterList.self,
                                          from: data)
            version = list.version
            expires = list.expires
            sources = list.sources
            rules = list.rules
        } catch {
            return nil
        }
    }
}
